In [ ]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/RodrigoARivasG/etl-data-pipeline2509642022/refs/heads/main/data/raw/E_movimientos.csv")

df.head()

  id_movimiento id_inventario tipo_movimiento       fecha cantidad_movimiento
0       MOV9000       INV5000          ajuste  2025-03-05                  15
1       MOV9001       INV5122          ajuste  2024-03-06              73 uds
2       MOV9002       INV5019          salida  2024-05-27                  30
3       MOV9003       INV5110         entrada  2025-01-16                  44
4       MOV9004       INV5152         entrada  2024-08-28                  55

In [ ]:
df.columns

Index(['id_movimiento', 'id_inventario', 'tipo_movimiento', 'fecha',
       'cantidad_movimiento'],
      dtype='object')

LIMPIEZA DE DATOS

In [20]:
movimientos = df.copy()

# Normalizar nombres de columnas
movimientos.columns = movimientos.columns.str.strip().str.lower()

# Reemplazar vacíos por NA
movimientos = movimientos.replace(r'^\s*$', pd.NA, regex=True)
movimientos = movimientos.replace(['nan', 'None', 'none', '-', '<na>', '<Na>', 'NaN'], pd.NA)

# Limpiar espacios en columnas de texto
for col in movimientos.select_dtypes(include="object").columns:
    movimientos[col] = movimientos[col].astype(str).str.strip()

# Convertir id_movimiento a numérico
movimientos['id_movimiento'] = pd.to_numeric(
    movimientos['id_movimiento'],
    errors='coerce'
)

# Convertir fecha a fecha
movimientos['fecha'] = pd.to_datetime(
    movimientos['fecha'],
    errors='coerce'
)

# Limpiar cantidad_movimiento: quitar texto no numérico (como "uds") y convertir a numérico
movimientos['cantidad_movimiento'] = (
    movimientos['cantidad_movimiento']
    .astype(str)
    .str.replace(r'\D', '', regex=True)  # Eliminar cualquier carácter no numérico
)

# Reemplazar valores vacíos con NaN antes de convertir a numérico
movimientos['cantidad_movimiento'] = pd.to_numeric(
    movimientos['cantidad_movimiento'],
    errors='coerce'
)

# Eliminar duplicados
movimientos = movimientos.drop_duplicates()

movimientos

,id_movimiento,id_inventario,tipo_movimiento,fecha,cantidad_movimiento
0,NaN,INV5000,ajuste,2025-03-05,15.0
1,NaN,INV5122,ajuste,2024-03-06,73.0
2,NaN,INV5019,salida,2024-05-27,30.0
3,NaN,INV5110,entrada,2025-01-16,44.0
4,NaN,INV5152,entrada,2024-08-28,55.0
...,...,...,...,...,...
215,NaN,INV5121,traslado,2024-11-07,31.0
216,NaN,INV5093,ajuste,2024-04-25,46.0
217,NaN,INV5107,entrada,2024-10-16,NaN
218,NaN,INV5032,traslado,2024-11-28,13.0
219,NaN,INV5107,ajuste,2024-08-05,30.0

In [21]:
movimientos.isna().sum()

id_movimiento          220
id_inventario            0
tipo_movimiento          0
fecha                   18
cantidad_movimiento      4
dtype: int64

SEPARAR DATOS VÁLIDOS E INVÁLIDOS

In [22]:
validos = movimientos[
    movimientos['id_movimiento'].notna() &
    movimientos['id_inventario'].notna() &
    movimientos['tipo_movimiento'].notna() &
    movimientos['fecha'].notna() &
    movimientos['cantidad_movimiento'].notna()
].copy()

rechazados = movimientos[
    movimientos['id_movimiento'].isna() |
    movimientos['id_inventario'].isna() |
    movimientos['tipo_movimiento'].isna() |
    movimientos['fecha'].isna() |
    movimientos['cantidad_movimiento'].isna()
].copy()

MOTIVO DE RECHAZO

In [23]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_movimiento']):
        motivos.append("id_movimiento_vacio")

    if pd.isna(row['id_inventario']):
        motivos.append("id_inventario_vacio")

    if pd.isna(row['tipo_movimiento']):
        motivos.append("tipo_movimiento_vacio")

    if pd.isna(row['fecha']):
        motivos.append("fecha_vacia_o_invalida")

    if pd.isna(row['cantidad_movimiento']):
        motivos.append("cantidad_movimiento_vacia_o_invalida")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

rechazados

,id_movimiento,id_inventario,tipo_movimiento,fecha,cantidad_movimiento,motivo_rechazo
0,NaN,INV5000,ajuste,2025-03-05,15.0,id_movimiento_vacio
1,NaN,INV5122,ajuste,2024-03-06,73.0,id_movimiento_vacio
2,NaN,INV5019,salida,2024-05-27,30.0,id_movimiento_vacio
3,NaN,INV5110,entrada,2025-01-16,44.0,id_movimiento_vacio
4,NaN,INV5152,entrada,2024-08-28,55.0,id_movimiento_vacio
...,...,...,...,...,...,...
215,NaN,INV5121,traslado,2024-11-07,31.0,id_movimiento_vacio
216,NaN,INV5093,ajuste,2024-04-25,46.0,id_movimiento_vacio
217,NaN,INV5107,entrada,2024-10-16,NaN,"id_movimiento_vacio,cantidad_movimiento_vacia_..."
218,NaN,INV5032,traslado,2024-11-28,13.0,id_movimiento_vacio
219,NaN,INV5107,ajuste,2024-08-05,30.0,id_movimiento_vacio

CANTIDAD DE VÁLIDOS Y RECHAZADOS

In [24]:
print("Registros válidos:", len(validos))
print("Registros rechazados:", len(rechazados))

Registros válidos: 0
Registros rechazados: 220

EXPORTAR CSV

In [25]:
validos.to_csv("movimientos_curated.csv", index=False)
rechazados.to_csv("movimientos_rejects.csv", index=False)

INSTALAR BD

In [26]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_rivas:ks9EQNpC43n64cYY21G6e2BUn85omaRa@dpg-d6qu610gjchc73en58b0-a.oregon-postgres.render.com/etl_seguros_h814"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 39.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

CARGAR TABLAS A BD

In [27]:
validos.to_sql(
    'movimientos_curated',
    engine,
    if_exists='replace',
    index=False
)

rechazados.to_sql(
    'movimientos_rejects',
    engine,
    if_exists='replace',
    index=False
)

220

VERIFICAR DATOS

In [31]:
pd.read_sql(
    "SELECT * FROM movimientos_curated LIMIT 10",
    engine
)

Empty DataFrame
Columns: [id_movimiento, id_inventario, tipo_movimiento, fecha, cantidad_movimiento]
Index: []

In [30]:
pd.read_sql(
    "SELECT * FROM movimientos_rejects LIMIT 10",
    engine
)

,id_movimiento,id_inventario,tipo_movimiento,fecha,cantidad_movimiento,motivo_rechazo
0,None,INV5000,ajuste,2025-03-05,15.0,id_movimiento_vacio
1,None,INV5122,ajuste,2024-03-06,73.0,id_movimiento_vacio
2,None,INV5019,salida,2024-05-27,30.0,id_movimiento_vacio
3,None,INV5110,entrada,2025-01-16,44.0,id_movimiento_vacio
4,None,INV5152,entrada,2024-08-28,55.0,id_movimiento_vacio
5,None,INV5133,traslado,2024-03-21,17.0,id_movimiento_vacio
6,None,INV5115,traslado,NaT,39.0,"id_movimiento_vacio,fecha_vacia_o_invalida"
7,None,INV5093,ajuste,2025-06-15,48.0,id_movimiento_vacio
8,None,INV5119,entrada,2025-01-31,3.0,id_movimiento_vacio
9,None,INV5112,ajuste,2025-07-04,37.0,id_movimiento_vacio